/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.Sistema;
import Backend.Gestor;
import javax.swing.JOptionPane;
import Serializacao.Serializacao;

/**
 *
 * @author josep
 */
public class EditarGestor extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao serializacao;
    private Gestor gestor;
    private listarGestores listagemGestores;

    public EditarGestor(Sistema sistema, Serializacao serializacao, listarGestores listagemGestores, Gestor gestor) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        this.sistema = sistema;
        this.serializacao = serializacao;
        this.listagemGestores = listagemGestores;
        this.gestor = gestor;

        if (registoNovo()) {
            setTitle("Criação de um novo Gestor");
            txtUsername.requestFocus();
        } else {
            setTitle("Alteração de dados de Gestor");
            txtNome.setEditable(false);
            txtUsername.setText(gestor.getUsername());
            txtPass.setText(gestor.getPassword());
            txtNome.setText(gestor.getNome());

        }
    }

    private void guardar() {

        if (txtUsername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. o Username!");
            txtUsername.requestFocus();
            return;
        }
        if (txtPass.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. a Password!");
            txtPass.requestFocus();
            return;
        }
        if (txtConfPass.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. a Password de confirmação!");
            txtConfPass.requestFocus();
            return;
        }
        if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. o Nome!");
            txtNome.requestFocus();
            return;
        }

        String password = new String(txtPass.getPassword());

        if (!password.equals(new String(txtConfPass.getPassword()))) {
            JOptionPane.showMessageDialog(this, "A password de confirmação não corresponde à password introduzida!");
            txtConfPass.requestFocus();
            return;
        }

        if (registoNovo()) {
            Gestor novo = new Gestor();
            novo.setUsername(txtUsername.getText());
            novo.setPassword(password);
            novo.setNome(txtNome.getText());
            sistema.getListaGestores().adicionarGestor(novo);
            fechar();
        } else {
            gestor.setUsername(txtUsername.getText());
            gestor.setPassword(password);
            fechar();
        }

        if (listagemGestores != null) {
            listagemGestores.atualizar();
        }

        JOptionPane.showMessageDialog(this, "Registo guardado com sucesso.");

    }

    private void fechar() {
        dispose();
        listarGestores lg = new listarGestores(sistema, serializacao);
        lg.setVisible(true);
    }

    private boolean registoNovo() {
        return gestor == null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        txtConfPass = new javax.swing.JPasswordField();
        txtNome = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Gestor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 128, 39));

        lbUsername.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbUsername.setForeground(new java.awt.Color(0, 204, 255));
        lbUsername.setText("USERNAME:");
        jPanel1.add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 41));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 160, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 43));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("Confirmar Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, 45));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setText("Nome:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 108, 41));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 255));
        jButton1.setText("Voltar");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 100, 30));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, 30));
        jPanel1.add(txtConfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 160, 30));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 160, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 255));
        jButton2.setText("Guardar");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 90, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login-image.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 369));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        listarGestores lg = new listarGestores(sistema, serializacao);
        lg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        guardar();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPasswordField txtConfPass;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
