/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.CentroVacinacao;
import Backend.Gestor;
import Backend.ListaEfeitos;
import Backend.RepositorioDoencas;
import Serializacao.Serializacao;
import Backend.Sistema;
import Backend.Utente;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author josep
 */
public class EfeitosSecundarios extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao serializacao;
    private Utente utente;
    private LocalDateTime hora;
    private ConsultarMarcacoesGestor listagem2;

    /**
     * Creates new form EfeitosSecundarios
     */
    public EfeitosSecundarios(Sistema sistema, Serializacao serializacao, Utente utente, LocalDateTime hora, ConsultarMarcacoesGestor listagem2) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.sistema = sistema;
        this.serializacao = serializacao;
        this.utente = utente;
        this.hora = hora;
        this.listagem2 = listagem2;
    }

    public void add() {
        if (txtEfeitos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza um efeito!");
            txtEfeitos.requestFocus();
            return;
        }
        CentroVacinacao centro = sistema.getListaCentros().procurarCentro((Gestor) sistema.getUtilizadorLigado());
        ListaEfeitos lista = centro.getListaEfeitos();

        if (lista == null) {
            ListaEfeitos listaEfeitosTemp = new ListaEfeitos();

            listaEfeitosTemp.adicionarEfeito(txtEfeitos.getText());
            centro.setListaEfeitos(listaEfeitosTemp);
            sistema.getListaEfeitos().adicionarEfeito(txtEfeitos.getText());

        } else {
            if (lista.existeEfeito(txtEfeitos.getText())) {
                JOptionPane.showMessageDialog(this, "Já existe este efeito secundário no sistema!");
                return;
            }
            lista.adicionarEfeito(txtEfeitos.getText());
            centro.setListaEfeitos(lista);
            sistema.getListaEfeitos().adicionarEfeito(txtEfeitos.getText());

        }
        JOptionPane.showMessageDialog(this, "Doenca adicionada com sucesso");
        txtEfeitos.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEfeitos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("EFEITOS SECUNDÁRIOS APÓS A INOCULAÇÃO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 40));

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("Insira a reação após a toma da vacina :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 280, 30));
        getContentPane().add(txtEfeitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 150, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 255));
        jButton1.setText("Voltar");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 73, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 255));
        jButton2.setText("Add");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 71, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login-image.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 453, 323));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        RegistarInoculacao ri = new RegistarInoculacao(sistema, serializacao, utente, hora, listagem2);
        ri.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        add();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtEfeitos;
    // End of variables declaration//GEN-END:variables
}
