/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Serializacao.Serializacao;
import Backend.Sistema;
import Backend.Administrador;
import Backend.Gestor;
import Backend.Utente;
import javax.swing.JOptionPane;

/**
 *
 * @author josep
 */
public class janelaAdmin extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao serializacao;

    /**
     * Creates new form janelaPrincipal
     */
    public janelaAdmin(Sistema sistema, Serializacao serializacao) {
        initComponents();
        this.sistema = sistema;
        this.serializacao = serializacao;
        this.setResizable(false);
        this.setLocationRelativeTo(null);

    }

    private void centros() {
        listarCentros lc = new listarCentros(sistema, serializacao);
        lc.setVisible(true);
        this.dispose();
    }

    private void gestores() {
        listarGestores lg = new listarGestores(sistema, serializacao);
        lg.setVisible(true);
        this.dispose();
    }

    private void consultarTomas() {
        int soma = 0;
        for (Utente utente : sistema.getListaUtentes().getLista()) {
            soma += utente.getNumTomas();
        }
        if (soma == 0) {
            JOptionPane.showMessageDialog(this, "Ainda ninguém levou a primeira toma!");
            return;
        }
        ConsultarTomas ct = new ConsultarTomas(sistema, serializacao);
        ct.setVisible(true);
        this.dispose();
    }

    private void consultarEfeitos() {
        if (sistema.getListaEfeitos().getEfeitos().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Não existem efeitos secundários no sistema!");
            return;
        }
        ConsultarEfeitosSecundarios ces = new ConsultarEfeitosSecundarios(sistema, serializacao);
        ces.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        btnGestor = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCentro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 255));
        jButton3.setText("Sair");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 99, 40));

        btnGestor.setBackground(new java.awt.Color(255, 255, 255));
        btnGestor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnGestor.setForeground(new java.awt.Color(0, 204, 255));
        btnGestor.setText("Consultar Gestores");
        btnGestor.setBorderPainted(false);
        btnGestor.setPreferredSize(new java.awt.Dimension(183, 183));
        btnGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestorActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 240, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 255));
        jButton2.setText("Consultar efeitos secundários");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 240, 40));

        btnCentro.setBackground(new java.awt.Color(255, 255, 255));
        btnCentro.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCentro.setForeground(new java.awt.Color(0, 204, 255));
        btnCentro.setText("Consultar Centros de Vacinação");
        btnCentro.setBorderPainted(false);
        btnCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 240, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 255));
        jButton1.setText("Consultar número de tomas");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 240, 40));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("ADMINISTRADOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login-image.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentroActionPerformed
        centros();
    }//GEN-LAST:event_btnCentroActionPerformed

    private void btnGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestorActionPerformed
        gestores();
    }//GEN-LAST:event_btnGestorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        consultarTomas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        consultarEfeitos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        janelaLogin jl = new janelaLogin(sistema, serializacao);
        jl.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCentro;
    private javax.swing.JButton btnGestor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
