/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Serializacao.Serializacao;
import Backend.Sistema;
import Backend.CentroVacinacao;
import Backend.Utente;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author josep
 */
public class JanelaUtente extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao serializacao;

    public JanelaUtente(Sistema sistema, Serializacao serializacao) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.sistema = sistema;
        this.serializacao = serializacao;

        Utente utente = (Utente) sistema.getUtilizadorLigado();

        if (utente.getCentroVac() != null) {
            btEscolher.setVisible(false);
        }

    }

    public void registarDoenca() {
        RegistarDoencas rd = new RegistarDoencas(sistema, serializacao);
        rd.setVisible(true);
    }

    public void escolherCentro() {
        if (sistema.getListaCentros().todos().isEmpty()) {
            JOptionPane.showMessageDialog(this, " Ainda não existem centros de Vacinação no sistema!");
            return;
        }
        EscolherCentro ec = new EscolherCentro(sistema, serializacao);
        ec.setVisible(true);
        this.dispose();
    }

    public void consultarCentro() {
        Utente utente = (Utente) sistema.getUtilizadorLigado();
        CentroVacinacao centro = utente.getCentroVac();
        if (centro == null) {
            JOptionPane.showMessageDialog(this, "Você ainda não tem Centro de Vacinação associado",
                    "Centro de Vacinação em falta", JOptionPane.WARNING_MESSAGE);
        } else {
            ConsultarCentro cc = new ConsultarCentro(sistema, serializacao);
            cc.setVisible(true);
            this.dispose();
        }
    }

    public void fazerMarcacao() {

        FazerMarcacao fm = new FazerMarcacao(sistema, serializacao);
        fm.setVisible(true);

    }

    public void consultarMarcacao() {
        Utente utente = (Utente) sistema.getUtilizadorLigado();
        ArrayList<Utente> u = new ArrayList<>();
        u.add(utente);
        if (sistema.getListaCentros().todos().isEmpty()) {
            JOptionPane.showMessageDialog(this, " Ainda não existem centros de Vacinação no sistema!");
            return;
        }

        if (utente.getCentroVac().getMarcacoes() == null) {
            JOptionPane.showMessageDialog(this, " Ainda não existem marcacões para este centro!");
            return;
        }

        if (utente.getCentroVac().getMarcacoes().getHoraUtente(u) == null) {
            JOptionPane.showMessageDialog(this, "Ainda não existe marcação");
            return;
        }

        ConsultarMarcacao cm = new ConsultarMarcacao(sistema, serializacao);
        cm.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btRegistar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btEscolher = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Utente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 107, 31));

        btRegistar.setBackground(new java.awt.Color(255, 255, 255));
        btRegistar.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        btRegistar.setForeground(new java.awt.Color(0, 204, 255));
        btRegistar.setText("REGISTAR DOENÇA");
        btRegistar.setBorderPainted(false);
        btRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistarActionPerformed(evt);
            }
        });
        jPanel1.add(btRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 210, 42));

        btConsultar.setBackground(new java.awt.Color(255, 255, 255));
        btConsultar.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        btConsultar.setForeground(new java.awt.Color(0, 204, 255));
        btConsultar.setText("CONSULTAR CENTRO");
        btConsultar.setBorderPainted(false);
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, 210, 40));

        btEscolher.setBackground(new java.awt.Color(255, 255, 255));
        btEscolher.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        btEscolher.setForeground(new java.awt.Color(0, 204, 255));
        btEscolher.setText("ESCOLHER CENTRO");
        btEscolher.setBorderPainted(false);
        btEscolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEscolherActionPerformed(evt);
            }
        });
        jPanel1.add(btEscolher, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 54, 179, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 255));
        jButton1.setText("FAZER MARCAÇÃO");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 210, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 255));
        jButton2.setText("CONSULTAR MARCAÇÃO");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, 210, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 255));
        jButton3.setText("Sair");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login-image.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 450, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 454, 324));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistarActionPerformed
        registarDoenca();
        this.dispose();
    }//GEN-LAST:event_btRegistarActionPerformed

    private void btEscolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEscolherActionPerformed
        escolherCentro();
    }//GEN-LAST:event_btEscolherActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultarCentro();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fazerMarcacao();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        consultarMarcacao();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        janelaLogin jl = new janelaLogin(sistema, serializacao);
        jl.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btEscolher;
    private javax.swing.JButton btRegistar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
