/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Serializacao.Serializacao;
import Backend.Sistema;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import Backend.Utente;
import Backend.CentroVacinacao;

/**
 *
 * @author josep
 */
public class janelaRegistar extends javax.swing.JFrame {

    private Serializacao serializacao;
    private Sistema sistema;

    /**
     * Creates new form registar
     */
    public janelaRegistar(Serializacao serializacao, Sistema sistema) {
        initComponents();
        //Não permite o redimensionamento da janela
        this.setResizable(false);

        //Mostra a centralização da janela
        this.setLocationRelativeTo(null);
        this.serializacao = serializacao;
        this.sistema = sistema;

    }
    //lista

    private void registar() {

        if (txtUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. o seu username!");
            txtUser.requestFocus();
            return;
        }

        if (txtPass.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. a sua password!");
            txtPass.requestFocus();
            return;
        }

        if (txtConfPass.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. a password de confirmação!");
            txtConfPass.requestFocus();
            return;
        }

        if (txtContacto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. o seu contacto telefonico!");
            txtContacto.requestFocus();
            return;
        }

        if (txtDataNasc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. a sua data de nascimento!");
            txtDataNasc.requestFocus();
            return;
        }

        if (txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. o seu Email!");
            txtEmail.requestFocus();
            return;
        }

        if (txtLocalidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. a sua localidade!");
            txtLocalidade.requestFocus();
            return;
        }

        if (txtMorada.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. a sua morada!");
            txtMorada.requestFocus();
            return;
        }

        if (txtSns.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. o seu número SNS!");
            txtSns.requestFocus();
            return;
        }

        if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza p.f. o seu nome!");
            txtNome.requestFocus();
            return;
        }

        String password = new String(txtPass.getPassword());

        if (!password.equals(new String(txtConfPass.getPassword()))) {
            JOptionPane.showMessageDialog(this, "A password de confirmação não corresponde à password introduzida!");
            txtConfPass.requestFocus();
            return;
        }

        int sns = Integer.parseInt(txtSns.getText());
        if (sistema.getListaUtentes().verificarExisteUtente(sns)) {
            JOptionPane.showMessageDialog(this, "Este utente já existe no Sistema");
            return;
        }

        LocalDate dataBirth = LocalDate.parse(txtDataNasc.getText());
        int Ntel = Integer.parseInt(txtContacto.getText());

        Utente novo = new Utente();
        novo.setNome(txtNome.getText());
        novo.setUsername(txtUser.getText());
        novo.setPassword(password);
        novo.setEmail(txtEmail.getText());
        novo.setNumUtente(sns);
        novo.setData_nasc(dataBirth);
        novo.setContacto(Ntel);
        novo.setMorada(txtMorada.getText());
        novo.setLocalidade(txtLocalidade.getText());

        for (CentroVacinacao centro : sistema.getListaCentros().todos()) {
            if (novo.getLocalidade() == centro.getLocalidade()) {
                novo.setCentroVac(centro);
            }

        }

        sistema.getListaUtentes().adicionarUtente(novo);
        JOptionPane.showMessageDialog(this, "Registo efectuado com sucesso.");
        dispose();
        janelaLogin jr = new janelaLogin(sistema, serializacao);
        jr.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCentro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCentro = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lbUser1 = new javax.swing.JLabel();
        lbPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        lbConfPass = new javax.swing.JLabel();
        txtConfPass = new javax.swing.JPasswordField();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jbSns = new javax.swing.JLabel();
        txtSns = new javax.swing.JTextField();
        lbMorada = new javax.swing.JLabel();
        txtMorada = new javax.swing.JTextField();
        lbLocalidade = new javax.swing.JLabel();
        txtLocalidade = new javax.swing.JTextField();
        lbDataNasc = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        lbContacto = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        lbCentro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCentro.setText("Centro Vacinacao:");

        listCentro.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCentro.setEnabled(false);
        jScrollPane1.setViewportView(listCentro);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(8, 44, 191));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("REGISTAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 39));
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 191, 36));

        lbUser1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lbUser1.setForeground(new java.awt.Color(0, 204, 255));
        lbUser1.setText("USERNAME:");
        jPanel1.add(lbUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 111, 49));

        lbPass.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lbPass.setForeground(new java.awt.Color(0, 204, 255));
        lbPass.setText("PASSWORD:");
        jPanel1.add(lbPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 38));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 118, 191, 40));

        lbConfPass.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lbConfPass.setForeground(new java.awt.Color(0, 204, 255));
        lbConfPass.setText("CONFIRMAR PASS:");
        jPanel1.add(lbConfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 147, 37));

        txtConfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfPassActionPerformed(evt);
            }
        });
        jPanel1.add(txtConfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 191, 40));

        lbNome.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lbNome.setForeground(new java.awt.Color(0, 204, 255));
        lbNome.setText("NOME:");
        jPanel1.add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 227, 147, 51));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 191, 40));

        jbSns.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jbSns.setForeground(new java.awt.Color(0, 204, 255));
        jbSns.setText("Nº SNS:");
        jPanel1.add(jbSns, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 291, 125, 47));
        jPanel1.add(txtSns, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 191, 40));

        lbMorada.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lbMorada.setForeground(new java.awt.Color(0, 204, 255));
        lbMorada.setText("Morada:");
        jPanel1.add(lbMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 353, 107, 44));
        jPanel1.add(txtMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 191, 40));

        lbLocalidade.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lbLocalidade.setForeground(new java.awt.Color(0, 204, 255));
        lbLocalidade.setText("LOCALIDADE:");
        jPanel1.add(lbLocalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 125, 46));
        jPanel1.add(txtLocalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 191, 40));

        lbDataNasc.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lbDataNasc.setForeground(new java.awt.Color(0, 204, 255));
        lbDataNasc.setText("DATA NASC:");
        jPanel1.add(lbDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 147, 56));
        jPanel1.add(txtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 191, 40));

        lbContacto.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lbContacto.setForeground(new java.awt.Color(0, 204, 255));
        lbContacto.setText("CONTACTO:");
        jPanel1.add(lbContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 147, 43));
        jPanel1.add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 191, 40));

        lbEmail.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(0, 204, 255));
        lbEmail.setText("EMAIL:");
        jPanel1.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 147, 60));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 191, 44));

        btGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btGuardar.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        btGuardar.setForeground(new java.awt.Color(0, 204, 255));
        btGuardar.setText("Guardar");
        btGuardar.setBorderPainted(false);
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 29, 107, 33));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 255));
        jButton1.setText("Voltar");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        registar();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtConfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        janelaLogin jr = new janelaLogin(sistema, serializacao);
        jr.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbSns;
    private javax.swing.JLabel lbCentro;
    private javax.swing.JLabel lbConfPass;
    private javax.swing.JLabel lbContacto;
    private javax.swing.JLabel lbDataNasc;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbLocalidade;
    private javax.swing.JLabel lbMorada;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbUser1;
    private javax.swing.JList<String> listCentro;
    private javax.swing.JPasswordField txtConfPass;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLocalidade;
    private javax.swing.JTextField txtMorada;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtSns;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
