/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Serializacao.Serializacao;
import Backend.Sistema;
import Backend.RepositorioDoencas;
import Backend.Utente;
import javax.swing.JOptionPane;

/**
 *
 * @author josep
 */
public class RegistarDoencas extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao serializacao;

    /**
     * Creates new form RegistarDoencas
     */
    public RegistarDoencas(Sistema sistema, Serializacao serializacao) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.sistema = sistema;
        this.serializacao = serializacao;

    }

    public void addDoenca() {
        if (txtDoenca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza uma Doenca!");
            txtDoenca.requestFocus();
            return;
        }
        Utente utente = (Utente) sistema.getUtilizadorLigado();
        RepositorioDoencas doencas = utente.getDoencas();
        if (doencas == null) {
            RepositorioDoencas doencasTemp = new RepositorioDoencas();

            doencasTemp.adicionarDoencas(txtDoenca.getText());
            utente.setDoencas(doencasTemp);

        } else {
            if (doencas.existeDoenca(txtDoenca.getText())) {
                JOptionPane.showMessageDialog(this, "Já existe esta doença associada a este utente");
                return;
            }
            doencas.adicionarDoencas(txtDoenca.getText());
            utente.setDoencas(doencas);

        }
        JOptionPane.showMessageDialog(this, "Doenca adicionada com sucesso");
        txtDoenca.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbRegistar = new javax.swing.JLabel();
        lbDoenca = new javax.swing.JLabel();
        txtDoenca = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbRegistar.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lbRegistar.setForeground(new java.awt.Color(0, 204, 255));
        lbRegistar.setText("REGISTAR DOENÇA");
        jPanel1.add(lbRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 41));

        lbDoenca.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lbDoenca.setForeground(new java.awt.Color(0, 204, 255));
        lbDoenca.setText("Insira a sua doenca:");
        jPanel1.add(lbDoenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 31));
        jPanel1.add(txtDoenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 192, 31));

        btAdd.setBackground(new java.awt.Color(255, 255, 255));
        btAdd.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        btAdd.setForeground(new java.awt.Color(0, 204, 255));
        btAdd.setText("Adicionar");
        btAdd.setBorderPainted(false);
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        jPanel1.add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 100, 30));

        btFechar.setBackground(new java.awt.Color(255, 255, 255));
        btFechar.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        btFechar.setForeground(new java.awt.Color(0, 204, 255));
        btFechar.setText("Voltar");
        btFechar.setBorderPainted(false);
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        jPanel1.add(btFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login-image.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        dispose();
        JanelaUtente ju = new JanelaUtente(sistema, serializacao);
        ju.setVisible(true);
    }//GEN-LAST:event_btFecharActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        addDoenca();
    }//GEN-LAST:event_btAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDoenca;
    private javax.swing.JLabel lbRegistar;
    private javax.swing.JTextField txtDoenca;
    // End of variables declaration//GEN-END:variables

}
